// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACockQrxQDuQNIruW0IVhPiV4ydivGZtY',
    appId: '1:825924884813:android:6acae59d2633ab01b7bf04',
    messagingSenderId: '825924884813',
    projectId: 'fastable-cde05',
    storageBucket: 'fastable-cde05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_N1QSCK_ctk1AwgmF_66aqBk3cqcqRh0',
    appId: '1:825924884813:ios:6d9f1884c0e23ee6b7bf04',
    messagingSenderId: '825924884813',
    projectId: 'fastable-cde05',
    storageBucket: 'fastable-cde05.firebasestorage.app',
    androidClientId: '825924884813-83u4q0jri7jmu9pcp57miehavn4a4gpt.apps.googleusercontent.com',
    iosClientId: '825924884813-jl425q7cn1n6232u04gcthjer29u898b.apps.googleusercontent.com',
    iosBundleId: 'com.midas.fastable',
  );

}